### ISSUE TITLE
Highlighting a single kanji and pressing 削 throws TypeError

### ISSUE THREAD

**Issue by shanrauf** [migaku-official/Migaku-Japanese-Addon#18]
#### Nature of issue?
- Found a bug

#### Details about the bug: 
When highlighting a single kanji and pressing the 削 button, this error is thrown:
`TypeError: wrapSelection is not a function or its return value is not iterable`

The fact that the error mentions something about not being iterable makes me think the error is related to the fact that a single kanji/word is being highlighted as opposed to a whole selection that has been parsed by the addon.

**Comment by KieranMigaku** [comment]
We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.
