### ISSUE TITLE
GPLv3 License Change Not Enforceable

### ISSUE THREAD

**Issue by cyphar** [migaku-official/Migaku-Japanese-Addon#69]
I honestly don't have any opinion on the rest of the drama going on at the moment, but the most recent change to the license is not actually enforceable for the following reasons:

1. The GPLv3 explicitly does not allow you to "impose any further restrictions on the exercise of the rights granted or affirmed under this License." (&sect;10) and all users are allowed to remove the the restrictions "If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term." (&sect;7). Therefore adding these restrictions is a strict no-op because any users can remove them.

2. All Anki add-ons must be released under an AGPLv3-compatible license (technically they need to be under the AGPLv3 because they are derivative works, but [the AnkiWeb terms allow you to use an AGPLv3-compatible license](https://ankiweb.net/account/terms) -- "As add-ons extend the computer version, they must be licensed under the AGPL3 or a compatible license."). This license with restrictions (assuming they were enforceable) is not AGPLv3-compatible.

3. For some of the Migaku add-ons, you are not the only contributor to the project, and in order to change the license of a project you must get approval from every contributor which has made a significant change (the FSF classifies this as more than 15 lines of code). This doesn't appear to apply to the Japanese add-on but it does appear to apply to the Dictionary add-on as far as I can tell.

You've also changed the copyright lines in the README, from "Copyright © 2019 Mass Immersion Approach" to "Copyright © 2020 Migaku Ltd". I don't know what the legal status of "Mass Immersion Approach" is (you mention in your video that it was a partnership but not an actual company), but you simply cannot unilaterally change the copyright holders of a work. (I get that you developed the add-ons, but it didn't say "Copyright © 2019 Yoga" -- though this can get quite complicated when it comes to copyright assignment, personally this is something I would just avoid touching altogether.)

Believe me, I do understand why you feel the need to do what you're doing (I have watched the video you posted) -- but you simply aren't allowed to impose these restrictions and (as someone who has been developing free software for most of my life now), whenever someone misunderstands the GPL and tries to restrict users' freedoms it feels like a slap in the face. It adds insult to injury when you talk about wanting to "work with open source developers" but at the same time you're imposing restrictions that make your code no longer open source / free software. I love free software, and it hurts to see this sort of thing happen.

(For the record, I'm saying this as someone who was considering contributing to this and other add-ons once I reached a point in my Japanese learning where I could make use of them.)

<hr/>

For reference the following text was added to the top of the GPLv3 license document:

> The GNU GENERAL PUBLIC LICENSE Version 3 license listed below is applicable in areas not conflicting with the following rules:
>
> 1. Any open-source Migaku project must be shared under the Migaku brand, name changes are not allowed. Additions to the default project names are however allowed. For example "Migaku Japanese - Extra Kanji Support Edition", which would be an appending of " - Extra Kanji Support Edition", to the default name of "Migaku Japanese".
>
> 2. When making a release of a fork whether publicly or privately a link to the official Migaku GitHub, the Migaku Patreon, and the Migaku Youtube Channel must also be provided.
>
> 3. Forks of an open-source Migaku project that is officially released on the AnkiWeb platform (https://ankiweb.net/shared/addons/) must not be released there.

**Comment by LucasMIA** [comment]
What "adds insult to injury" is building a brand together with a friend and then having them try to claim full ownership over it when you decide to leave because working together is untenable after you added a ton of value to it. You must understand how frustrating, and unexpected that is. 

Anyways, it's clear I am the author of these add-ons and I plan to continue developing them. I am all about having them be open source but it's pretty clear that whichever direction these projects go, that should fall under my brand. I released projects under the MIA brand on multiple occasions before we even combined Patreons, it's pretty clear that it was only due to us agreeing on an equal partnership that I ever chose to release anything in tandem with Matt vs. Japan. Any split with the MIA brand will include me keeping my work under my own brand and name. Anyways, I understand your position as far as open-source software goes though and, and rest assured that I hope when we are fully on the other side of this to embrace those same ideals with all future projects.

**Comment by cyphar** [comment]
Look, I get everyone is hot-headed right now -- I was just trying to point out that this *one particular thing* you decided to do is not acceptable (and it's not like you have a choice in the matter -- *all Anki add-ons are derivative works of Anki* which means that you need to license them under an AGPLv3-compatible license.) This is completely unrelated to questions of branding or whose name is on the project, or anything else for that matter.

(More importantly, as I said, the additional terms don't actually have any legal weight -- if you're worried about "someone" taking your project and selling it, they are entitled to do it under the terms of the license.)

**Comment by cyphar** [comment]
Not to add more fuel to the fire, but I just noticed that [`reading.py`](https://github.com/migaku-official/Migaku-Japanese-Addon/blob/bb899b964cff7a22523ab6a602ec6c0a1247be82/src/reading.py) appears to be a modified copy [of the same file in the Japanese Support add-on](https://github.com/ankitects/anki-addons/blob/07eacbec2631d88ae55538ba3b98f9416616135c/code/japanese/reading.py). This is all well and good, but two things:

* You appear to have stripped the copyright notice from the file -- this is not allowed at all, since the GPLv3 requires attribution and maintaining copyright notices.
* You can't change the license of code you didn't write.

**Comment by cyphar** [comment]
Fixed by 85beb5c02aef, thanks @LucasMIA.

**Comment by LucasMIA** [comment]
No problem bro, everything will be moved into compliance, I have full intents of going the open source route and want to show good faith to others in the open source community. I am too tired as I've been working for many days straight at the moment so will take a couple days off now, but please remind me in a few days if I forget to properly credit Damien by then, it's definitely not my intent not to do so. I will make a note to remember to this so I shouldn't forget though.
