### ISSUE TITLE
Rename Breaks Existing Cards on New Installs

### ISSUE THREAD

**Issue by cyphar** [migaku-official/Migaku-Japanese-Addon#70]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Linux

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no (at least, not until the project license is fixed)

**Description:**

If you had cards created under the old add-on (before the rename) and sync them to a new installation of Anki (which doesn't have the old configuration), the new add-on will no longer render them properly because the note type has changed (the mass rename included renaming the note types -- but existing cards will still use the old note type). Folks who directly upgraded (and thus have the old configuration) aren't affected by this.

Maybe the default configuration should include the old "MIA Japanese" note type as having active fields?

**Comment by cyphar** [comment]
Fixed by 85beb5c02aef8f600a07293a072116f410820ab, thanks @LucasMIA.

**Comment by LucasMIA** [comment]
This should be fixed now, can you confirm?

**Comment by cyphar** [comment]
Yeah I gave it a quick test before closing. With the default config you now get all the features for both the new and old note types.
