### ISSUE TITLE
Bulk generating reading/pitch accent on an edited* note type is messing the cards

### ISSUE THREAD

**Issue by Ceynou** [migaku-official/Migaku-Japanese-Addon#77]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
I edited my note type, swapped the positions with 2 fields, Sentence field ended where Screenshot field was, continued making card without restarting anki.
Bulk generating reading and pitch accent at the end of my card making session caused the image from the Screenshot filed to be duplicated into the sentence field.

I could revert that with ctrl+z but this is still a bug.
Thanks for the work.

**Comment by LucasMIA** [comment]
Please describe step by step how to replicate this issue or share a video showing the steps.

**Comment by Ceynou** [comment]
Might close the issue because I can't reproduce it consistently, had to mess with the step and I got lost, it happened again but it seems like it was only on one card.

There are three other issues that didn't seem to have been discussed, should I open those or you know about them?
- Launching anki and pressing ctrl+c+space on a japanese word without pressing ctrl+s first promt an error message.
- you need to press ctrl+c+space two time to get the definition to display, once only bring the dictionary window.
- definition content is what you copied(ctrl+z) from the dictionary window before clicking on the arrow to send to a field.

**Comment by KieranBrannigan** [comment]
Please feel free to make separate issues for those bugs and we can discuss them in their respective issues
