### ISSUE TITLE
Display pitch accent directly over the kana reading

### ISSUE THREAD

**Issue by archiif** [migaku-official/Migaku-Japanese-Addon#79]
**Type:**
  - [ ] bug
  - [ ] feature
  - [x] enhancement
  - [ ] question

**Environment:**
  - OS: Windows

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x] no

**Description:**
This feature is something that I think would be very helpful towards vocab card users. Right now, a vocab card made with Migaku would look something like this:
![image](https://user-images.githubusercontent.com/60074051/111782208-57671e80-88eb-11eb-9433-368d227dfdf3.png)
Now, if you want to quickly confirm where the drop in かける would be, you need to either:
- Mentally count the morae manually
- Hover over the kana reading.

So by allowing an option to display the pitch accent directly over the kana reading, it would greatly speed up the review process.

This may seem a bit fussy, but one of the nice benefits of vocab cards is just how fast you can blast through them, so I think this feature would greatly benefit the average vocab card user.

**Comment by LucasMIA** [comment]
We don't plan to add this feature, but feel free to open a pr if you'd like.

You can however export pitch graphs for the word which I feel covers the functionality you desire. Check out the guide on our site for more details.
